# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb1b3a9362ae0fa61ff0034e538136bcfc34097621aa8044995ac9d29cc824ec47673fb920c55e31da7ccc5f4585764b7ab0e0476fd6daef6efd0ceed266040d

test:
  secret_key_base: 10abfccf7fb69120c7b952f46c5932baf61da386ccc0e15d4ef4ed7f98c847f063a9fff58509e32ca7b0b036afa4c78f42a82d7923e24edf6826aa8eebaf9a62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
